name: CI/CD
on: workflow_dispatch
env:
    colors: ["red", "green"]
jobs:
    build:
        name: Build Mega Code
        uses: ./.github/workflows/m-build.yml
        with:
            color: ${{ matrix.color }}
    test:
        name: Test Mega Code
        needs: build
        uses: ./.github/workflows/m-test.yml
        with:
            color: ${{ matrix.color }}
