name: CI/CD
on: workflow_dispatch
jobs:
    build:
        name: Build Mega Code
        uses: ./.github/workflows/m-build.yml
        strategy:
            matrix:
                color: ["red"]
        with:
            color: ${{matrix.color}}
    test:
        name: Test Mega Code
        needs: build
        uses: ./.github/workflows/m-test.yml
        with:
            color: "red"
