name: CI/CD
on: workflow_dispatch
jobs:
    cicd:
        name: CI/CD
        strategy:
            matrix:
                color: ["red", "blue", "green"]
        uses: ./.github/workflows/m-build.yml
        with:
            color: ${{matrix.color}}
