name: Build Mega Code
on:
    workflow_call:
        inputs:
            color:
                type: string
                required: true
jobs:
    build:
        name: Build Mega Code
        runs-on: ubuntu-latest
        steps:
            - name: Building Mega Code
              run: echo "Building for ${{inputs.color}}"
