name: Deploy Mega Code
on:
    workflow_call:
        inputs:
            environment:
                type: string
                required: true
jobs:
    deploy-staging:
        name: Deploy Mega Code
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - run: echo "Deploying Mega Code to ${{inputs.environment}}"
