name: Deploy Mega Code
on:
    workflow_call:
        inputs:
            environment:
                type: string
                required: true
            color:
                type: string
                required: false
jobs:
    deploy-staging:
        name: Deploy Mega Code
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
            - run: echo "Deploying Mega Code to ${{inputs.environment}}"
            - if: ${{ inputs.color }}
              run: echo "Color is ${{inputs.color}}"
