name: Test Mega Code
on:
    workflow_call:
        inputs:
            color:
                type: string
                required: true
jobs:
    test:
        name: Test Mega Code
        runs-on: ubuntu-latest
        steps:
            - name: Testing Mega Code
              run: echo "Testing Mega Code color ${{inputs.color}}"
